# Shared settings
# ------------------------------
# These are shared configuration settings
# amongst each gallery (ios, mac, and applewatch)
# Site-specific configs are in each respective repo
email: jimniels@domain.com
baseurl: ""
assets:
    scripts: assets/scripts
    images: assets/img
    styles: assets/styles
sass:
    sass_dir: assets/styles/_sass
    style: :compressed
markdown: kramdown
permalink: /:year/:title
safe: false # use plugins
paginate_path: "p/:num"
source: .
destination: ./_site
exclude: 
    - README.md
    - .DS_STORE

# Defaults
defaults:
    -
        scope:
            path: "" # an empty string here means all files in the project
            type: "posts"
        values:
            layout: "posts"